### PR TITLE
Migration to autotools, i18n with gettext, revamped Preferences dialog UI and little improvements

### PR DESCRIPTION
**Pull request by frandieguez**
I have ported your extension for use autotools. This will allow to install your extension in a UNIX-way.

If you use Ubuntu you must install build-essential and libglib2.0-dev packages, if you are in fedora I guess you must install glib2-devel.

./autogen.sh
./configure --prefix=/usr
make
sudo make install

This will install the extension in /usr/share/gnome-shell/extensions, install gsettings schema and compile those schemas.

Indeed this will allow to generate rpm and deb packages for installing it from a repository.
Or generate tarballs by version, specifying the version in configure.ac by
./autogen.sh
./configure --prefix=/usr
make dist-bzip2

And if you use Gettext inside your extension you will allow others to localize it. I can translate the extension into Galician

### CODE REVIEW

**Comment by frandieguez** [comment]
I forgot something: I have added Spotify native client support

**Comment by frandieguez** [comment]
As you can see I have added i18n support for allow translating this extension. Added Galician translations too.
I had a little issue while sumit Preferences dialog (that python script is installed via autotools AM_PYTHON) cause is copied without execution flag. I changed all Utils.spawn forcing to use python to raise that dialog.

**Comment by frandieguez** [comment]
I added i18n to preferences dialog (with gettext python library) and made some clean up in its messages.

**Comment by frandieguez** [comment]
I have refactorized the Preferences dialog layout and drop the 'Choose a setup :' option from the combobox

**Comment by frandieguez** [comment]
I made some changes to solve some issues users reported to your issue tracker

**Comment by brianrobles204** [comment]
Wow, thanks for all this, really big help. I shall review and merge them when I get back to my main computer.

**Pull request merged**
